### ISSUE TITLE
MAC valid 

### ISSUE THREAD

**Issue by alzhao** [janost/openwrt-wan-mac#1]
The script don't generate a valid mac address every time.
It generate a random mac, e.g. ff:aa:..... is not a valid mac
While fe:aa:.... should be valid.

Pls check. 
https://superuser.com/questions/1210887/what-exactly-are-the-specifications-for-a-valid-mac-address

**Comment by DocSniper** [comment]
Change the line 
`NEWMAC=$(dd if=/dev/urandom bs=1024 count=1 2>/dev/null | md5sum | sed 's/^\(..\)\(..\)\(..\)\(..\)\(..\)\(..\).*$/\1:\2:\3:\4:\5:\6/') ` 
to
`NEWMAC=$(dd if=/dev/urandom bs=1024 count=1 2>/dev/null | md5sum | sed -e 's/^\(..\)\(..\)\(..\)\(..\)\(..\)\(..\).*$/\1:\2:\3:\4:\5:\6/' -e 's/^\(.\)[13579bdf]/\10/')`
then the MAC should be valid.

**Comment by janost** [comment]
I have no idea how I missed your issue for so long, I apologize.
Unfortunately I don't currently use an OpenWrt-based router, but will look into this as soon as I have a chance.

**Comment by janost** [comment]
The PR seems to fix the issue, thank you for reporting!
